minecraft-server:
  ports:
    - "25565:25565"
    - "25575:25575"

  volumes:
    - /Users/jdr/Dropbox (Personal)/Development/docker/containers/dockerfiles/minecraft-server/data:/data
  environment:
    - EULA=true
    - TYPE=SPIGOT
    - ENABLE_RCON=true
    - RCON_PASSWORD=testing
    - RCON_PORT=25575
    - ENABLE_QUERY=true
    - QUERY_PORT=25565
    - MODE=creative
    - FORCE_GAMEMODE=true
    - OPS=jdrivas
    - MOTD="Vanilla test server in a docker container."
    - ONLINE_MODE=false

  image: minecraft-itzg
  container_name: minecraft-server

  tty: true
  stdin_open: true
